In [8]:
import numpy as np
x1=list(map(int,input("x1: ").split()))
x2=list(map(int,input("x2: ").split()))
y=list(map(int,input("y: ").split()))
a=[]
for i in range(len(y)):
    a.append(1)
x=np.matrix([a,x1,x2])
print(x.T)
x=x.T
y=np.matrix(y)
y=y.T

x1: -5 -4 -1 2 2 3 3 
x2: 5 4 1 -3 -2 -2 -3
y: 11 11 8 2 5 5 4
[[ 1 -5  5]
 [ 1 -4  4]
 [ 1 -1  1]
 [ 1  2 -3]
 [ 1  2 -2]
 [ 1  3 -2]
 [ 1  3 -3]]


In [61]:
x=np.array(x)
print(x)

[[ 1 -5  5]
 [ 1 -4  4]
 [ 1 -1  1]
 [ 1  2 -3]
 [ 1  2 -2]
 [ 1  3 -2]
 [ 1  3 -3]]


In [9]:
xtx=np.dot(x.T,x)

In [10]:
print(xtx)
xtxinverse=np.linalg.inv(xtx)
print(xtxinverse)

[[  7   0   0]
 [  0  68 -67]
 [  0 -67  68]]
[[0.14285714 0.         0.        ]
 [0.         0.5037037  0.4962963 ]
 [0.         0.4962963  0.5037037 ]]


In [11]:
y=np.matrix(y)
abc=np.dot(x.T,y)
print(abc)

[[ 46]
 [-66]
 [ 69]]


In [16]:
xtxinxty=np.dot(xtxinverse,abc)
print(xtxinxty)

[[6.57142857]
 [1.        ]
 [2.        ]]


In [66]:
yhat=xtxinxty[0]+(xtxinxty[1]*x1)+(xtxinxty[2]*x2)
yhat=yhat.T
print(yhat)

<class 'numpy.matrix'>
[[11.57142857]
 [10.57142857]
 [ 7.57142857]
 [ 2.57142857]
 [ 4.57142857]
 [ 5.57142857]
 [ 3.57142857]]


In [113]:
error=np.subtract(y,yhat)

In [114]:
print(error)

[[-0.57142857]
 [ 0.42857143]
 [ 0.42857143]
 [-0.57142857]
 [ 0.42857143]
 [-0.57142857]
 [ 0.42857143]]


In [115]:
#sum of squares due to error
error=np.square(error)
sse=np.sum(error)
print("SSE =",sse)

SSE = 1.7142857142857144


In [116]:
#sum of squares due to total
ybar=np.mean(y)
print("ybar =",ybar)
y1=np.subtract(y,ybar)
y11= np.square(y1)
sst=np.sum(y11)
print("SST =",sst)

ybar = 6.571428571428571
SST = 73.71428571428571


In [117]:
#sum of squares due to regression
ssr=sst-sse
print("SSR =",ssr)

SSR = 72.0


In [118]:
#coefficient of determination
r2=ssr/sst
print("R^2 =",r2)

R^2 = 0.9767441860465117


In [119]:
if(r2>0.90):
    print("We accept H0")
else:
    print("We reject H0")

We accept H0
