In [21]:
import numpy as np

#reading inputs
x1=list(map(int,input("x1: ").split()))
x2=list(map(int,input("x2: ").split()))
y=list(map(int,input("y: ").split()))
a=[]
for i in range(len(y)):
    a.append(1)
x=np.matrix([a,x1,x2])
x=x.T
y=np.matrix(y)
y=y.T

#x matrix
x=np.array(x)
print("x\n",x)

#y matrix
print("y\n",y)

xtx=np.dot(x.T,x)
print("xTx\n",xtx)

xtxinverse=np.linalg.inv(xtx)
print("xTx-1\n",xtxinverse)

y=np.matrix(y)
xty=np.dot(x.T,y)
print("xTy\n",xty)

bcap=np.dot(xtxinverse,xty)
print("b^\n",bcap)

yhat=bcap[0]+(bcap[1]*x1)+(bcap[2]*x2)
yhat=yhat.T
print("y^",yhat)

error=np.subtract(y,yhat)
print("E\n",error)

x1: -5 -4 -1 2 2 3 3 
x2: 5 4 1 -3 -2 -2 -3
y: 11 11 8 2 5 5 4
x
 [[ 1 -5  5]
 [ 1 -4  4]
 [ 1 -1  1]
 [ 1  2 -3]
 [ 1  2 -2]
 [ 1  3 -2]
 [ 1  3 -3]]
y
 [[11]
 [11]
 [ 8]
 [ 2]
 [ 5]
 [ 5]
 [ 4]]
xTx
 [[  7   0   0]
 [  0  68 -67]
 [  0 -67  68]]
xTx-1
 [[0.14285714 0.         0.        ]
 [0.         0.5037037  0.4962963 ]
 [0.         0.4962963  0.5037037 ]]
xTy
 [[ 46]
 [-66]
 [ 69]]
b^
 [[6.57142857]
 [1.        ]
 [2.        ]]
y^ [[11.57142857]
 [10.57142857]
 [ 7.57142857]
 [ 2.57142857]
 [ 4.57142857]
 [ 5.57142857]
 [ 3.57142857]]
E
 [[-0.57142857]
 [ 0.42857143]
 [ 0.42857143]
 [-0.57142857]
 [ 0.42857143]
 [-0.57142857]
 [ 0.42857143]]


In [23]:
xtx=np.dot(x.T,x)
print("xTx\n",xtx)

xtxinverse=np.linalg.inv(xtx)
print("xTx-1\n",xtxinverse)

y=np.matrix(y)
xty=np.dot(x.T,y)
print("xTy\n",xty)

bcap=np.dot(xtxinverse,xty)
print("b^\n",bcap)

yhat=bcap[0]+(bcap[1]*x1)+(bcap[2]*x2)
yhat=yhat.T
print("y^",yhat)

error=np.subtract(y,yhat)
print("E\n",error)

xTx
 [[  7   0   0]
 [  0  68 -67]
 [  0 -67  68]]
xTx-1
 [[0.14285714 0.         0.        ]
 [0.         0.5037037  0.4962963 ]
 [0.         0.4962963  0.5037037 ]]
xTy
 [[ 46]
 [-66]
 [ 69]]
b^
 [[6.57142857]
 [1.        ]
 [2.        ]]
y^ [[11.57142857]
 [10.57142857]
 [ 7.57142857]
 [ 2.57142857]
 [ 4.57142857]
 [ 5.57142857]
 [ 3.57142857]]
E
 [[-0.57142857]
 [ 0.42857143]
 [ 0.42857143]
 [-0.57142857]
 [ 0.42857143]
 [-0.57142857]
 [ 0.42857143]]


In [24]:
# goodness of fit using anova
#sum of squares due to error
error=np.square(error)
sse=np.sum(error)
print("SSE =",sse)

#sum of squares due to total
ybar=np.mean(y)
print("ybar =",ybar)
y1=np.subtract(y,ybar)
y11= np.square(y1)
sst=np.sum(y11)
print("SST =",sst)

SSE = 1.7142857142857144
ybar = 6.571428571428571
SST = 73.71428571428571


In [25]:
#coefficient of determination
r2=ssr/sst
print("R^2 =",r2)

if(r2>0.90):
    print("We accept H0")
else:
    print("We reject H0")

R^2 = 0.9767441860465117
We accept H0


In [28]:
# goodness of fit using anova
#Anova one-way classification table
alpha=float(input("Enter the value of level of significance"))
p=3
n=len(y)
import pandas as pd
df=pd.read_excel("C:\\Users\\exam2\\Desktop\\book1.xlsx")
sof=[ssr,sse,sst]
df['sum of squares']=sof
dof=[p-1,n-p,n-1]
df['Degrees of freedom']=dof
msos=[sof[0]/dof[0],sof[1]/dof[1],'']
df['Mean sum of Squares']=msos
Fcal=msos[0]/msos[1]
vr=['',Fcal,'']
df['Variance Ratio']=vr
print(df)
print("Fcal=",Fcal)

Enter the value of level of significance0.05
  source of variation  sum of squares  Degrees of freedom Mean sum of Squares  \
0          regression       72.000000                   2                36.0   
1               error        1.714286                   4            0.428571   
2               total       73.714286                   6                       

  Variance Ratio  
0                 
1           84.0  
2                 
Fcal= 84.0


In [29]:
#Inference
import scipy.stats as s
Ftv=s.f.ppf(1-alpha,p-1,n-p)
print("Ftv=",Ftv)
if Fcal <= Ftv:
    print("We Accept Ho")
else:
    print("We Reject Ho")
    
#Calculating F value using Built in Functionk
import scipy.stats 
Fb=scipy.stats.f_oneway(a,x1,x2)
print("Fcal-b=",Fb)

Ftv= 6.944271909999155
We Reject Ho
Fcal-b= F_onewayResult(statistic=0.30882352941176483, pvalue=0.7381241403386867)
